baseURL = "http://stutzcoin.ch/"
languageCode = "en-us"
title = "STUTZ"
theme = "minimal"
googleAnalytics = ""


[params]
    author = "STUTZFoundation"
    description = "Putting your Räppli in Blöckli since 2018"
    favicon = "img/favicon.ico"
    navlogo ="/img/stutz_logo.png"
    githubUsername = "STUTZCoin"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/community/"
    name = "Community"
    weight = 2

[[menu.main]]
    url = "/wallet/"
    name = "Wallet"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:hoi@stutzcoin.ch"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/StutzCoin"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/stutzcoin/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://t.me/STUTZcoin"
    name = "telegram"
    weight = 4
